[package]
name = "brouillon"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
discrete_law = { version = "0.1.0", path = "../discrete_law" }
rand = "0.9.1"
rand_chacha = "0.9.0"
rand_pcg = "0.9.0"
