[package]
name = "discrete_law"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
iter_accumulate = "1.0.0"
ordered-float = { version = "5.0.0", features = ["bytemuck"] }
bytemuck = "1.22.0"
